{% set name = "megaradrp" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2badba11e4c0abbdbeb4ed74494964d11b01044dcab8aff66d8ae95397bc3c67

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - matplotlib-base
    - astropy >=2.0
    - scipy
    - numina >=0.22
    - scikit-image
    - jsonschema

test:
  imports:
    - megaradrp
    - megaradrp.core
    - megaradrp.core.tests
    - megaradrp.instrument
    - megaradrp.instrument.configs
    - megaradrp.instrument.components
    - megaradrp.processing
    - megaradrp.processing.tests
    - megaradrp.products
    - megaradrp.recipes
    - megaradrp.recipes.auxiliary
    - megaradrp.recipes.calibration
    - megaradrp.recipes.calibration.tests
    - megaradrp.recipes.combined
    - megaradrp.recipes.scientific
    - megaradrp.recipes.tests
    - megaradrp.schemas
    - megaradrp.simulation
    - megaradrp.tests
    - megaradrp.tools

about:
  home: https://github.com/guaix-ucm/megaradrp
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: MEGARA Data Reduction Pipeline
  description: |
    MEGARA is an optical integral-field Unit and multi-object spectrograph 
    instrument designed for the 10.4m telescope GTC. This package is
    the Data Reduction Pipeline for MEGARA
  doc_url: https://megaradrp.readthedocs.io/
  dev_url: https://github.com/guaix-ucm/megaradrp

extra:
  recipe-maintainers:
    - sergiopasra
