{% set name = "megaradrp" %}
{% set version = "0.7" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fa1cef8a580ee4df14bd0412e8324c60ddc583534c8574d16a5fd19da8b91dd6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - astropy >=1.0
    - scipy
    - numina >=0.16
    - scikit-image
    - enum34  # [py27]

test:
  imports:
    - megaradrp
    - megaradrp.core
    - megaradrp.core.tests
    - megaradrp.instrument
    - megaradrp.instrument.configs
    - megaradrp.processing
    - megaradrp.processing.tests
    - megaradrp.products
    - megaradrp.recipes
    - megaradrp.recipes.auxiliary
    - megaradrp.recipes.calibration
    - megaradrp.recipes.calibration.tests
    - megaradrp.recipes.combined
    - megaradrp.recipes.scientific
    - megaradrp.recipes.tests
    - megaradrp.simulation
    - megaradrp.tests

about:
  home: https://github.com/guaix-ucm/megaradrp
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: MEGARA Data Reduction Pipeline
  description: |
    MEGARA is an optical integral-field Unit and multi-object spectrograph 
    instrument designed for the 10.4m telescope GTC. This package is
    the Data Reduction Pipeline for MEGARA
  doc_url: https://megara-drp.readthedocs.io/
  dev_url: https://github.com/guaix-ucm/megaradrp

extra:
  recipe-maintainers:
    - sergiopasra
