{% set name = "megaradrp" %}
{% set version = "0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fd6230c1bb97ec9c9c0c97fb8e63447c3e82a79018f6b7bc1fd74943d74da79

build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - astropy-base >=2.0
    - jsonschema
    - matplotlib-base
    - numina >=0.33
    - numpy
    - packaging
    - scikit-image
    - scipy


test:
  imports:
    - megaradrp
    - megaradrp.core
    - megaradrp.core.tests
    - megaradrp.instrument
    - megaradrp.instrument.configs
    - megaradrp.instrument.components
    - megaradrp.processing
    - megaradrp.processing.tests
    - megaradrp.products
    - megaradrp.recipes
    - megaradrp.recipes.auxiliary
    - megaradrp.recipes.calibration
    - megaradrp.recipes.calibration.tests
    - megaradrp.recipes.combined
    - megaradrp.recipes.scientific
    - megaradrp.recipes.tests
    - megaradrp.schemas
    - megaradrp.simulation
    - megaradrp.tests
    - megaradrp.tools

about:
  home: https://github.com/guaix-ucm/megaradrp
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: MEGARA Data Reduction Pipeline
  description: |
    MEGARA is an optical integral-field Unit and multi-object spectrograph 
    instrument designed for the 10.4m telescope GTC. This package is
    the Data Reduction Pipeline for MEGARA
  doc_url: https://megaradrp.readthedocs.io/
  dev_url: https://github.com/guaix-ucm/megaradrp

extra:
  recipe-maintainers:
    - sergiopasra
