appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: LM9S+rhF7RnEV3qKMQwEh5jHH38b6uerocuRiqF0CrX41P+1vgV5MWmOpjKfKc6d67bDCkNoasMHJzvewNjdNGl2KAVOyQTVWp7G4YmfTG/Kj6u8Me7iIuYL2s1lyxGuIQrQggACKdRRZswEF7UAw4fiAw6CQweUdiOpVDGOIG136PCGUBwyDfn7tHHAegmlV2othIO4kCBGQYSpWFa1M5Q8Y3HRwEo++d2PVb+sih+tq3gs8vzXBpTTfTCtdLWXDkfABAYsyvbLtn3uuUKNxJRpB5hSJsiHCriIqOs+Cu4Z5VWh54AHZYigvDq8ipB9ZRujpgkD67UHuA/w/N8KKLT7UfArMIrD0kkPwOWCQdwpHvT/t6Q9cEVcPFc/V1O+KCYkZyDBkVVLg0ZBHt49F/POyqv75vAsnrOCU6RDndDTh+ppCh3A5cGlO0QKKbSsBNd3GTQQruE9u9GoouEUyJRMNsWNe45nYc4Vj1PbCRV+SGPdcl1kaXTNUzy3HeNMmvx5hmC90pmVxXHEqh0wuLZKZLTVUUg+sla5eDgv7Jzg2edC92/lwl58rKycJ/5Ez10zpPvyDSl1vZ/0MmrJ8EXuMlCFzyx6TGliQHMvgCGg6FGaKWPf47FIrighzu9+tcAatgfW1idu7RFYSEC6J5drgB/rPjCwnvRAPuKz6v4=}
provider:
  win: azure
conda_forge_output_validation: true
